services:
  postgres:
    image: postgres:16-alpine3.19
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: techimpact
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
